INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('LOG9', 'LOG', 'logo test', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="LOG9" typecode="LOG" typedescr="Logo"><descr>logo test</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Logo" attributetype="Image"><resource resourcetype="Image" id="7" lang="en" /><text lang="en">ttt</text></attribute></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140508161402</created><lastModified>20140603155803</lastModified></content>
', '20140508161402', '20140603155803', '<?xml version="1.0" encoding="UTF-8"?>
<content id="LOG9" typecode="LOG" typedescr="Logo"><descr>logo test</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Logo" attributetype="Image"><resource resourcetype="Image" id="7" lang="en" /><text lang="en">ttt</text></attribute></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140508161402</created><lastModified>20140603155803</lastModified></content>
', 'free', '2.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG38', 'CNG', 'Sample Slide 4', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG38" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 4</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 4</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 4</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 4</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">slide 4</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>3.0</version><lastEditor>admin</lastEditor><created>20140509113752</created><lastModified>20140627112741</lastModified></content>
', '20140509113752', '20140627112741', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG38" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 4</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 4</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 4</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 4</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">slide 4</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>3.0</version><lastEditor>admin</lastEditor><created>20140509113752</created><lastModified>20140627112741</lastModified></content>
', 'free', '3.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS88', 'NWS', 'Sample - News 1', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS88" typecode="NWS" typedescr="News"><descr>Sample - News 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', '20140527174451', '20140527174451', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS88" typecode="NWS" typedescr="News"><descr>Sample - News 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS89', 'NWS', 'Sample - News 2', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS89" typecode="NWS" typedescr="News"><descr>Sample - News 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 2</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', '20140527174451', '20140527174451', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS89" typecode="NWS" typedescr="News"><descr>Sample - News 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 2</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS90', 'NWS', 'Sample - News 3', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS90" typecode="NWS" typedescr="News"><descr>Sample - News 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 3</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', '20140527174451', '20140527174451', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS90" typecode="NWS" typedescr="News"><descr>Sample - News 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 3</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS91', 'NWS', 'Sample - News 4', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS91" typecode="NWS" typedescr="News"><descr>Sample - News 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 4</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', '20140527174451', '20140527174451', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS91" typecode="NWS" typedescr="News"><descr>Sample - News 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 4</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS92', 'NWS', 'Sample - News 5', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS92" typecode="NWS" typedescr="News"><descr>Sample - News 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 5</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', '20140527174451', '20140527174451', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS92" typecode="NWS" typedescr="News"><descr>Sample - News 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 5</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174451</created><lastModified>20140527174451</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS93', 'NWS', 'Sample - News 6', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS93" typecode="NWS" typedescr="News"><descr>Sample - News 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 6</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', '20140527174452', '20140527174452', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS93" typecode="NWS" typedescr="News"><descr>Sample - News 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 6</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link"><attribute name="Links" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN94', 'ANN', 'Sample - Announcement 1', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN94" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 1.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', '20140527174452', '20140527174452', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN94" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 1.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN95', 'ANN', 'Sample - Announcement 2', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN95" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 2.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', '20140527174452', '20140527174452', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN95" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 2.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN96', 'ANN', 'Sample - Announcement 3', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN96" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 3.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', '20140527174452', '20140527174452', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN96" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 3.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN97', 'ANN', 'Sample - Announcement 4', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN97" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 4.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', '20140527174452', '20140527174452', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN97" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 4.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG114', 'CNG', 'Homepage - Main Content', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG114" typecode="CNG" typedescr="Generic Content"><descr>Homepage - Main Content</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Homepage Main Content</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. We need to neutralize the homing signal. Each unit has total environmental control, gravity, temperature, atmosphere, light, in a protective field. Sensors show energy readings in your area. We had a forced chamber explosion in the resonator coil. Field strength has increased by 3,000 percent.</p>
<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. We need to neutralize the homing signal. Each unit has total environmental control, gravity, temperature, atmosphere, light, in a protective field. Sensors show energy readings in your area. We had a forced chamber explosion in the resonator coil. Field strength has increased by 3,000 percent.</p>
<p>
	We&#39;re acquainted with the wormhole phenomenon, but this... Is a remarkable piece of bio-electronic engineering by which I see much of the EM spectrum ranging from heat and infrared through radio waves, et cetera, and forgive me if I&#39;ve said and listened to this a thousand times. This planet&#39;s interior heat provides an abundance of geothermal energy. We need to neutralize the homing signal.</p>
<p>
	Sensors indicate no shuttle or other ships in this sector. According to coordinates, we have travelled 7,000 light years and are located near the system J-25. Tractor beam released, sir. Force field maintaining our hull integrity. Damage report? Sections 27, 28 and 29 on decks four, five and six destroyed. Without our shields, at this range it is probable a photon detonation could destroy the Enterprise.</p>
<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><lastEditor>admin</lastEditor><lastModified>20140603102310</lastModified></content>
', '20140603102201', '20140603102310', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG114" typecode="CNG" typedescr="Generic Content"><descr>Homepage - Main Content</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Homepage Main Content</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. We need to neutralize the homing signal. Each unit has total environmental control, gravity, temperature, atmosphere, light, in a protective field. Sensors show energy readings in your area. We had a forced chamber explosion in the resonator coil. Field strength has increased by 3,000 percent.</p>
<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. We need to neutralize the homing signal. Each unit has total environmental control, gravity, temperature, atmosphere, light, in a protective field. Sensors show energy readings in your area. We had a forced chamber explosion in the resonator coil. Field strength has increased by 3,000 percent.</p>
<p>
	We&#39;re acquainted with the wormhole phenomenon, but this... Is a remarkable piece of bio-electronic engineering by which I see much of the EM spectrum ranging from heat and infrared through radio waves, et cetera, and forgive me if I&#39;ve said and listened to this a thousand times. This planet&#39;s interior heat provides an abundance of geothermal energy. We need to neutralize the homing signal.</p>
<p>
	Sensors indicate no shuttle or other ships in this sector. According to coordinates, we have travelled 7,000 light years and are located near the system J-25. Tractor beam released, sir. Force field maintaining our hull integrity. Damage report? Sections 27, 28 and 29 on decks four, five and six destroyed. Without our shields, at this range it is probable a photon detonation could destroy the Enterprise.</p>
<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><lastEditor>admin</lastEditor><lastModified>20140603102310</lastModified></content>
', 'free', '1.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN99', 'ANN', 'Sample - Announcement 6', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN99" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 6.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', '20140527174452', '20140527174452', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN99" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 6.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN98', 'ANN', 'Sample - Announcement 5', 'DRAFT', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN98" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 5.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br />
	Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p>
<p>
	Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>DRAFT</status><version>1.1</version><lastEditor>admin</lastEditor><created>20140527174452</created><lastModified>20140527175328</lastModified></content>
', '20140527174452', '20140527175328', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN98" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 5.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list name="Documents" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20140527174452</created><lastModified>20140527174452</lastModified></content>
', 'free', '1.1', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG31', 'CNG', 'Test Content', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG31" typecode="CNG" typedescr="Generic Content"><descr>Test Content</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Content 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text"><text lang="en">Something like a caption here</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>6.0</version><lastEditor>admin</lastEditor><created>20140509095726</created><lastModified>20140603102639</lastModified></content>
', '20140509095726', '20140603102639', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG31" typecode="CNG" typedescr="Generic Content"><descr>Test Content</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Content 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text"><text lang="en">Something like a caption here</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>6.0</version><lastEditor>admin</lastEditor><created>20140509095726</created><lastModified>20140603102639</lastModified></content>
', 'free', '6.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG145', 'CNG', 'About Us', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG145" typecode="CNG" typedescr="Generic Content"><descr>About Us</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">About Us</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text"><text lang="en">Something like a caption here</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140509095726</created><lastModified>20140603105844</lastModified></content>
', '20140603105753', '20140603105844', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG145" typecode="CNG" typedescr="Generic Content"><descr>About Us</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">About Us</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text"><text lang="en">Something like a caption here</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140509095726</created><lastModified>20140603105844</lastModified></content>
', 'free', '2.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG152', 'CNG', 'Contact Us', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG152" typecode="CNG" typedescr="Generic Content"><descr>Contact Us</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Contact Us</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text"><text lang="en">Something like a caption here</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><lastEditor>admin</lastEditor><created>20140509095726</created><lastModified>20140603110001</lastModified></content>
', '20140603105955', '20140603110001', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG152" typecode="CNG" typedescr="Generic Content"><descr>Contact Us</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Contact Us</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	These are the voyages of the Starship Enterprise. Its continuing mission, to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no one has gone before. Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text"><text lang="en">Something like a caption here</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><lastEditor>admin</lastEditor><created>20140509095726</created><lastModified>20140603110001</lastModified></content>
', 'free', '1.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('VID173', 'VID', 'Sample Video 1', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="VID173" typecode="VID" typedescr="Video"><descr>Sample Video 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Video 1</text></attribute><attribute name="Date" attributetype="Date"><date>20140603</date></attribute><attribute name="Desc" attributetype="Longtext"><text lang="en">Video Description</text></attribute><attribute name="Video" attributetype="Monotext"><monotext>07uGW6Jjibc</monotext></attribute><attribute name="Provider" attributetype="Enumerator"><monotext>youtube</monotext></attribute></attributes><status>PUBLIC</status><version>1.0</version><lastEditor>admin</lastEditor><lastModified>20140603181328</lastModified></content>
', '20140603181222', '20140603181328', '<?xml version="1.0" encoding="UTF-8"?>
<content id="VID173" typecode="VID" typedescr="Video"><descr>Sample Video 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Video 1</text></attribute><attribute name="Date" attributetype="Date"><date>20140603</date></attribute><attribute name="Desc" attributetype="Longtext"><text lang="en">Video Description</text></attribute><attribute name="Video" attributetype="Monotext"><monotext>07uGW6Jjibc</monotext></attribute><attribute name="Provider" attributetype="Enumerator"><monotext>youtube</monotext></attribute></attributes><status>PUBLIC</status><version>1.0</version><lastEditor>admin</lastEditor><lastModified>20140603181328</lastModified></content>
', 'free', '1.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('VID175', 'VID', 'Sample Video 2', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="VID175" typecode="VID" typedescr="Video"><descr>Sample Video 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Video 2</text></attribute><attribute name="Date" attributetype="Date"><date>20140603</date></attribute><attribute name="Desc" attributetype="Longtext"><text lang="en">Video Description</text></attribute><attribute name="Video" attributetype="Monotext"><monotext>87955153</monotext></attribute><attribute name="Provider" attributetype="Enumerator"><monotext>vimeo</monotext></attribute></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140603181222</created><lastModified>20140603182147</lastModified></content>
', '20140603182029', '20140603182147', '<?xml version="1.0" encoding="UTF-8"?>
<content id="VID175" typecode="VID" typedescr="Video"><descr>Sample Video 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Video 2</text></attribute><attribute name="Date" attributetype="Date"><date>20140603</date></attribute><attribute name="Desc" attributetype="Longtext"><text lang="en">Video Description</text></attribute><attribute name="Video" attributetype="Monotext"><monotext>87955153</monotext></attribute><attribute name="Provider" attributetype="Enumerator"><monotext>vimeo</monotext></attribute></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140603181222</created><lastModified>20140603182147</lastModified></content>
', 'free', '2.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG245', 'CNG', 'Activiti', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG245" typecode="CNG" typedescr="Generic Content"><descr>Activiti</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Activiti</text></attribute><attribute name="Abstract" attributetype="Hypertext" /><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<ul>
	<li>
		<a href="#!P;act_vacation_request!#">Vacation Request</a></li>
	<li>
		<a href="#!P;vacation_request!#">List of vacation requests</a></li>
	<li>
		<a href="#!P;process_list!#">Process list</a></li>
	<li>
		<a href="#!P;task_list!#">Task list</a></li>
	<li>
		<a href="#!P;task_list!#">Handle Vacation Request</a></li>
	<li>
		<a href="#!P;iframe!#">IFRAME</a></li>
</ul>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140626114537</created><lastModified>20140626114908</lastModified></content>
', '20140626114537', '20140626114908', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG245" typecode="CNG" typedescr="Generic Content"><descr>Activiti</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Activiti</text></attribute><attribute name="Abstract" attributetype="Hypertext" /><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<ul>
	<li>
		<a href="#!P;act_vacation_request!#">Vacation Request</a></li>
	<li>
		<a href="#!P;vacation_request!#">List of vacation requests</a></li>
	<li>
		<a href="#!P;process_list!#">Process list</a></li>
	<li>
		<a href="#!P;task_list!#">Task list</a></li>
	<li>
		<a href="#!P;task_list!#">Handle Vacation Request</a></li>
	<li>
		<a href="#!P;iframe!#">IFRAME</a></li>
</ul>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20140626114537</created><lastModified>20140626114908</lastModified></content>
', 'free', '2.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG26', 'CNG', 'Sample Slide 1', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG26" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 1</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Shields up. I recommend we transfer power to phasers and arm the photon torpedoes.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Something strange on the detector circuit. The weapons must have disrupted our communicators. You saw something as tasty as meat, but inorganically materialized out of patterns used by our transporters. Captain, the most elementary and valuable statement in science, the beginning of wisdom, is &#39;I do not know.&#39; All transporters off.</p>
<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">Logo</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>5.0</version><lastEditor>admin</lastEditor><created>20140508173752</created><lastModified>20140627112635</lastModified></content>
', '20140508173752', '20140627112635', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG26" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 1</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Shields up. I recommend we transfer power to phasers and arm the photon torpedoes.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Something strange on the detector circuit. The weapons must have disrupted our communicators. You saw something as tasty as meat, but inorganically materialized out of patterns used by our transporters. Captain, the most elementary and valuable statement in science, the beginning of wisdom, is &#39;I do not know.&#39; All transporters off.</p>
<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">Logo</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>5.0</version><lastEditor>admin</lastEditor><created>20140508173752</created><lastModified>20140627112635</lastModified></content>
', 'free', '5.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG54', 'CNG', 'Sample Slide 2', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG54" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 2</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 2</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 2</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 2</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">logo 2</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>3.0</version><lastEditor>admin</lastEditor><created>20140509113752</created><lastModified>20140627112656</lastModified></content>
', '20140515110431', '20140627112656', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG54" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 2</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 2</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 2</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 2</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">logo 2</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>3.0</version><lastEditor>admin</lastEditor><created>20140509113752</created><lastModified>20140627112656</lastModified></content>
', 'free', '3.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG56', 'CNG', 'Sample Slide 3', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG56" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 3</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 3</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">logo</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>3.0</version><lastEditor>admin</lastEditor><created>20140509113752</created><lastModified>20140627112720</lastModified></content>
', '20140515110510', '20140627112720', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG56" typecode="CNG" typedescr="Generic Content"><descr>Sample Slide 3</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 3</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Resistance is futile.</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">logo</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>3.0</version><lastEditor>admin</lastEditor><created>20140509113752</created><lastModified>20140627112720</lastModified></content>
', 'free', '3.0', 'admin');
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG255', 'CNG', 'aqweqw', 'READY', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG255" typecode="CNG" typedescr="Generic Content"><descr>aqweqw</descr><groups mainGroup="free" /><categories><category id="slide" /></categories><attributes><attribute name="Title" attributetype="Text"><text lang="en">Sample Slide 4</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 4</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	Sample Slide 4</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="249" lang="en" /><text lang="en">slide 4</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">test image</text></attribute><list name="Links" attributetype="Monolist" nestedtype="Link" /><list name="Attaches" attributetype="Monolist" nestedtype="Attach" /></attributes><status>READY</status><version>0.1</version><lastEditor>admin</lastEditor><created>20140509113752</created><lastModified>20140707165322</lastModified></content>
', '20140707165322', '20140707165322', NULL, 'free', '0.1', 'admin');
