INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('7', 'Image', 'test logo', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="7"><descr>test logo</descr><groups mainGroup="free" /><categories /><masterfile>logo-enterprise.png</masterfile><instance><size>3</size><filename>logo-enterprise_d3.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>2</size><filename>logo-enterprise_d2.png</filename><mimetype>image/png</mimetype><weight>1 Kb</weight></instance><instance><size>1</size><filename>logo-enterprise_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>logo-enterprise_d0.png</filename><mimetype>image/png</mimetype><weight>9 Kb</weight></instance></resource>
', 'logo-enterprise.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('32', 'Attach', 'test attach', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Attach" id="32"><descr>test attach</descr><groups mainGroup="free" /><categories /><masterfile>lorem.txt</masterfile><instance><size>0</size><filename>lorem.txt</filename><mimetype>text/plain</mimetype><weight>0 Kb</weight></instance></resource>
', 'lorem.txt');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('249', 'Image', 'logo entando bianco', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="249"><descr>logo entando bianco</descr><groups mainGroup="free" /><categories /><masterfile>entando-logo-white.png</masterfile><instance><size>3</size><filename>entando-logo-white_d3.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>2</size><filename>entando-logo-white_d2.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>1</size><filename>entando-logo-white_d1.png</filename><mimetype>image/png</mimetype><weight>0 Kb</weight></instance><instance><size>0</size><filename>entando-logo-white_d0.png</filename><mimetype>image/png</mimetype><weight>17 Kb</weight></instance></resource>
', 'entando-logo-white.png');
INSERT INTO resources (resid, restype, descr, maingroup, resourcexml, masterfilename) VALUES ('261', 'Image', 'Logo', 'free', '<?xml version="1.0" encoding="UTF-8"?>
<resource typecode="Image" id="261"><descr>Logo</descr><groups mainGroup="free" /><categories /><masterfile>new_logo.jpg</masterfile><instance><size>3</size><filename>new_logo_d3.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>2</size><filename>new_logo_d2.jpg</filename><mimetype>image/jpeg</mimetype><weight>2 Kb</weight></instance><instance><size>1</size><filename>new_logo_d1.jpg</filename><mimetype>image/jpeg</mimetype><weight>1 Kb</weight></instance><instance><size>0</size><filename>new_logo_d0.jpg</filename><mimetype>image/jpeg</mimetype><weight>29 Kb</weight></instance></resource>
', 'new_logo.jpg');
